parameters:
    metas:
        title:              'Asphalt Legends Unite'
        author:             'Giancarlo PALUMBO'
        email:              'giancarlo.palumbo@free.fr'
        description:        ~
        generator:          ~
    classes:
        table:              'table table-bordered table-striped text-light'
        td:                 'my-0 py-0 align-middle'
        btn:                'btn btn-sm btn-outline-info rounded-3 py-1 m-0'
        input:              'text-center fw-bolder form-control-sm form-control'
#        input:              'text-center fw-bolder form-control-plaintext form-control-sm'
    games:
        pack:               6
        pack_price:         900
    images:
        avatar:             'images/sako-01.jpg'
when@dev:
    parameters:
        cache_lifetime:
            dashboards:     60  # 1 min
            garages:        60  # 1 min
            missions:       60  # 1 min
            races:          60  # 1 min
            sitemaps:       300  # 5 mins
            statistics:     300  # 5 mins
        images:
            logo:           'images/logo-green.png'
when@prod:
    parameters:
        cache_lifetime:
            dashboards:     3600    # (60 * 60 = 1 hour)
            garages:        3600    # (60 * 60 = 1 hour)
            missions:       3600    # (60 * 60 = 1 hour)
            races:          2678400 # (60 * 60 * 24 * 31 = 1 month)
            sitemaps:       2678400 # (60 * 60 * 24 * 31 = 1 month)
            statistics:     2678400 # (60 * 60 * 24 * 31 = 1 month)
        images:
            logo:           'images/logo-white.png'
